### ISSUE TITLE
Re: previous issues and small typo.

### ISSUE THREAD

**Issue by Anntoin** [lambdalisue/vim-shareboard#1]
The issues that I [mentioned](https://github.com/lambdalisue/vim-pandoc-preview/issues/1) are fixed in version 0.1.6 and it's working well. Only small issue I could see is that I think `textlie.vim` is a typo - should it be textile?

I thought others using Arch might find it handy so I put up packages of shareboard[1](https://aur.archlinux.org/packages/python2-shareboard-git/) and shareboard.vim[2](https://aur.archlinux.org/packages/vim-shareboard-git/) on the Arch user repository, hope that's okay.

**Comment by lambdalisue** [comment]
Thanks for your report. Yes it's typo :-p

I already fixed that and bumped the version to 0.1.4. I also add [Advanced usage](https://github.com/lambdalisue/shareboard.vim#advanced-usage) to `README.md` so please use this latest version to bundle the package of Arch linux :-)

I'm realy grad to hear that my library goes into a package, make sure that [PySide](http://qt-project.org/wiki/PySide) and [Qt](http://qt.digia.com/) are included in that package otherwise shareboard.vim wount work :-)

P.S.
Tell me when you made the package, I'd like to add the link to `README.md` :-)

**Comment by Anntoin** [comment]
Hi, the packages are source build scripts that track the current git master so they should stay up to date, PySide and Qt are mentioned as dependencies too.
The packages are here:
https://aur.archlinux.org/packages/python2-shareboard-git/
https://aur.archlinux.org/packages/vim-shareboard-git/

It'd be cool if you linked to them :)
