### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lingnand** [lambdalisue/vim-shareboard#2]
Just tried it on Arch Linux and it's not working.

When I try shareboard myself using 'shareboard start -v' and shareboard set' it's working OK; but if I use the vimscript it doesn't display anything.

I notice that in the vimscript there's an argument '--filename' passed to shareboard; but trying it out myself on the command line returns 'unrecognized arguments --filename ...'

**Comment by lambdalisue** [comment]
I'm sorry for late reply. Well, `--filename` argument is only for `set` command. So the following command should work properly.

```
$ shareboard set "Hello" --filename "Hello.html"
```

Quick question, are you using PROXY? I had similar problem in my work computer and the reason was PROXY.
If you are using proxy, set `NO_PROXY` and `no_proxy` variable like below. It might help.

```
# .bashrc
export NO_PROXY="127.0.0.1,localhost"
export no_proxy="$NO_PROXY"
```

Or your `pandoc` might not be able to see from Vim. If `!which pandoc` said pandoc is not found, then add extra PATH in your vimrc like https://github.com/lambdalisue/dotfiles/blob/master/vim/vimrc#L425
